import type { Metadata } from "next";
import { cairoli } from "@/utils/customfonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairoli.variable} antialiased bg-black`}>
        {children}
      </body>
    </html>
  );
}
